// AUDIT ONLY: test existing contracts; transpilation output is an isolated cache.
import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import * as THREE from 'three';import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
const dir='.cache/post-mvp-audit-tests';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'package.json'),'{"type":"module"}');
for(const name of ['SceneCompiler','TowerCompiler','AutoPlacer','FurnitureFactory','TextureGenerator']){let js=ts.transpileModule(fs.readFileSync(`apps/web/src/components/scene-compiler/${name}.ts`,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.ES2020}}).outputText;js=js.replace(/from ["']\.\/(\w+)["']/g,"from './$1.js'");fs.writeFileSync(path.join(dir,name+'.js'),js);}
const {validateManifest,SceneIndex}=await import('../../.cache/post-mvp-audit-tests/model.js');const {SceneCompiler}=await import('../../.cache/post-mvp-audit-tests/SceneCompiler.js');
const manifest=JSON.parse(fs.readFileSync('apps/web/public/models/duplex/manifest.json','utf8'));const b=fs.readFileSync('apps/web/public/models/duplex/duplex.glb');const {scene}=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');const results=[];
for(const [name,mutate] of [['duplicate-element-id',m=>m.elements[1].id=m.elements[0].id],['empty-unit-id',m=>m.floors[1].flats[0].id=''],['nan-element-bounds',m=>m.elements[0].bounds=[[NaN,0,0],[1,1,1]]]]){const m=structuredClone(manifest);mutate(m);try{validateManifest(m,scene);results.push({name,rejected:false});}catch(e){results.push({name,rejected:true,message:String(e)});}}
const index=new SceneIndex(scene,manifest);results.push({name:'sample-semantic-maps',byRoom:index.byRoom.size,byFlat:index.byFlat.size,byFloor:index.byFloor.size,walls:index.walls.length,doors:index.doors.length});
const generated=new SceneCompiler({structureJson:{walls:[{id:'w1',startX:0,startZ:0,endX:4,endZ:0,height:3,thickness:.15}],rooms:[],furniture:[],apertures:[{id:'window1',type:'window',wallId:'w1',startOffset:1,width:1,height:1.2,elevation:.9}]}}).compile();const generatedIndex=new SceneIndex(generated);let windowMeshes=0;generated.traverse(n=>{if(n instanceof THREE.Mesh&&n.parent?.name==='window_assembly_window1')windowMeshes++;});results.push({name:'generated-window-collision-index',windowMeshes,indexedWindowMeshes:generatedIndex.walls.filter(m=>m.parent?.name==='window_assembly_window1').length,wallColliderMeshes:generatedIndex.walls.length});
fs.writeFileSync('evidence/post-mvp-audit/extended-tests.json',JSON.stringify(results,null,2));console.log(results);
