const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11']});const results=[];
const record=(name,details={})=>{results.push({name,result:'PASS',...details});console.log(JSON.stringify(results.at(-1)));fs.writeFileSync('evidence/performance/verification.json',JSON.stringify(results,null,2));};
const check=async(name,fn)=>{try{const details=await fn();record(name,details);}catch(e){results.push({name,result:'FAIL',error:String(e)});console.error(results.at(-1));fs.writeFileSync('evidence/performance/verification.json',JSON.stringify(results,null,2));}};
const login=async(page,port,email)=>{await page.goto('http://localhost:'+port+'/login',{waitUntil:'networkidle'});await page.locator('input[type=email]').fill(email);await page.locator('input[type=password]').fill('password');await page.locator('button[type=submit]').click();await page.waitForURL('http://localhost:'+port+'/');await page.waitForLoadState('networkidle');};
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await check('Explorer navigation stays stable and renderer survives sidebar changes',async()=>{await page.goto('http://localhost:3000/explorer',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('[data-testid=property-canvas]')?.getViewerSnapshot?.().state.manifest);assert.equal(await page.locator('[data-testid=site-header]').count(),0);assert.equal(await page.locator('#site-sidebar').getAttribute('data-expanded'),'true');const snapshot=()=>page.locator('[data-testid=property-canvas]').evaluate(e=>e.getViewerSnapshot());const initial=await snapshot();const before=await page.locator('#site-sidebar').boundingBox();await page.mouse.move(300,300);await page.mouse.move(50,300);assert.equal((await page.locator('#site-sidebar').boundingBox()).width,before.width);await page.getByRole('button',{name:'Collapse sidebar',exact:true}).click();assert.equal((await snapshot()).rootId,initial.rootId);assert.equal((await snapshot()).stats.rendererId,initial.stats.rendererId);await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('#site-sidebar').getAttribute('data-expanded'),'false');await page.getByRole('button',{name:'Expand sidebar',exact:true}).click();await page.screenshot({path:'evidence/performance/final-explorer.png'});return{headerHidden:true,defaultSidebarWidth:before.width};});
 await check('Public inventory displays API units and retains the selected builder',async()=>{const builder=await fetch('http://localhost:3001/builders/theme-by-slug/aethelgard').then(r=>r.json());const towers=await fetch('http://localhost:3001/inventory/towers',{headers:{'x-tenant-id':builder.id}}).then(r=>r.json());const first=towers[0].floors.flatMap(f=>f.flats)[0];await page.goto('http://localhost:3000/inventory?builder=aethelgard',{waitUntil:'networkidle'});assert((await page.locator('section[aria-label="Available homes"]').innerText()).includes(first.flatNumber));await page.getByRole('link',{name:'View details',exact:true}).click();await page.waitForLoadState('networkidle');assert.equal(new URL(page.url()).searchParams.get('builder'),'aethelgard');assert((await page.locator('[aria-label="Selected home"]').innerText()).includes(first.flatNumber));await page.goto('http://localhost:3000/inventory?builder=omniestate',{waitUntil:'networkidle'});assert(!(await page.locator('#page-content').innerText()).includes(first.flatNumber));await page.locator('#site-nav-links').getByRole('link',{name:'3D Explorer',exact:true}).click();await page.waitForURL(/builder=omniestate/);return{selectedHome:first.flatNumber};});
 await check('Failed inventory requests show an error and recover on retry',async()=>{const context=await browser.newContext();const p=await context.newPage();let fail=true;await p.route('**/inventory/towers',r=>fail?r.fulfill({status:503,json:{message:'Temporarily unavailable'}}):r.continue());await p.goto('http://localhost:3000/inventory',{waitUntil:'networkidle'});await p.locator('#page-content').getByRole('alert').waitFor();assert((await p.locator('#page-content').getByRole('alert').innerText()).includes('Temporarily unavailable'));fail=false;await p.getByRole('button',{name:'Try again',exact:true}).click();await p.locator('section[aria-label="Available homes"]').waitFor();await context.close();});
 await check('Unknown builder and unit show clear states rather than invented listing details',async()=>{await page.goto('http://localhost:3000/inventory?builder=missing-builder-qa',{waitUntil:'networkidle'});await page.locator('#page-content').getByRole('alert').waitFor();await page.goto('http://localhost:3000/inventory/missing-unit?builder=aethelgard',{waitUntil:'networkidle'});await page.getByRole('heading',{name:'This home could not be found'}).waitFor();});
 await check('Mobile explorer navigation opens, closes, and keeps content within the screen',async()=>{await page.setViewportSize({width:390,height:844});await page.goto('http://localhost:3000/explorer',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Open navigation',exact:true}).click();assert(await page.locator('#site-sidebar').isVisible());await page.keyboard.press('Escape');assert(!(await page.locator('#site-sidebar').isVisible()));const widths=await page.evaluate(()=>({width:innerWidth,content:document.documentElement.scrollWidth}));assert(widths.content<=widths.width+2);await page.screenshot({path:'evidence/performance/final-explorer-mobile.png'});return widths;});
 for(const [port,email] of [[3002,'admin@platform.com'],[3003,'admin@aethelgard.com'],[3003,'admin@omniestate.com']]){await check('Portal refresh and mobile navigation: '+email,async()=>{const context=await browser.newContext({viewport:{width:390,height:844}}),p=await context.newPage();await login(p,port,email);await p.reload({waitUntil:'networkidle'});await p.locator('[aria-label="Loading workspace"]').waitFor({state:'hidden'});assert.equal(new URL(p.url()).pathname,'/');await p.getByRole('button',{name:'Open navigation',exact:true}).click();await p.getByRole('button',{name:'Sign Out',exact:true}).or(p.getByRole('button',{name:'Sign out',exact:true})).click();await p.waitForURL('http://localhost:'+port+'/login');await context.close();});}
 await check('AI floor-plan requests use the logged-in OmniEstate tenant',async()=>{const context=await browser.newContext(),p=await context.newPage();await login(p,3003,'admin@omniestate.com');const auth=await p.evaluate(()=>JSON.parse(sessionStorage.getItem('aether-builder-auth')).state);const headers=[];p.on('request',r=>{if(r.url().includes('localhost:3001/floorplans'))headers.push(r.headers()['x-tenant-id']);});await p.goto('http://localhost:3003/ai-generator',{waitUntil:'networkidle'});assert(headers.length>0);assert(headers.every(value=>value===auth.user.tenantId));await context.close();return{tenantRequests:headers.length};});
 record('No browser errors in public interaction checks',{errors});assert.equal(errors.length,0);
 await page.close();
}finally{await browser.close();}
if(results.some(r=>r.result==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
