const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),THREE=require('three');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11']});const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(20000);const results=[],errors=[],details=[];page.on('pageerror',e=>errors.push(e.message));
const test=async(name,fn)=>{try{await fn();results.push({name,result:'PASS'});}catch(e){results.push({name,result:'FAIL',reason:String(e)});}console.log(results.at(-1));};
const snapshot=()=>page.locator('[data-testid=property-canvas]').evaluate(e=>e.getViewerSnapshot());
const ready=()=>page.waitForFunction(()=>!!document.querySelector('[data-testid=property-canvas]')?.getViewerSnapshot?.().state.manifest);
let apiMode='empty';await page.route(/(?:localhost:3001|trycloudflare\.com)\//,r=>{const url=r.request().url();let data=[];if(apiMode==='embed'&&url.includes('/sdk/embeds/resolve'))data={tenantId:'offline',floorPlans:[],data:[{model:{id:'bsi-duplex-v1',projectId:'offline-project',name:'Duplex Apartment',modelUrl:'/models/duplex/duplex.glb',manifestUrl:'/models/duplex/manifest.json',modelType:'exterior'},hotspots:[],tours:[]}]};if(apiMode.startsWith('legacy')){if(url.includes('theme-by-slug'))data={id:'offline',name:'Aether'};else if(url.endsWith('/digital-twin/models'))data=[{id:'exterior',projectId:'offline',name:'Exterior',modelType:'exterior',modelUrl:''},{id:'interior',projectId:'offline',name:'Interior',modelType:'interior',modelUrl:''}];else if(apiMode==='legacy-inventory'&&url.endsWith('/inventory/towers'))data=[{id:'qa-tower',projectId:'offline',name:'QA tower'}];else if(apiMode==='legacy-inventory'&&url.includes('/inventory/towers/qa-tower/floors')){const layout=JSON.parse(fs.readFileSync('apps/web/public/models/dxf-fixture.json','utf8'));data=Array.from({length:10},(_,i)=>({id:`qa-floor-${i}`,floorNumber:i,floorHeight:3,structureJson:{...layout,rooms:layout.rooms.map(r=>({...r,flatId:`${i+1}01`}))}}));}else if(apiMode==='legacy-inventory'&&url.includes('/inventory/flats?'))data=Array.from({length:10},(_,i)=>({id:`qa-flat-${i}`,flatNumber:`${i+1}01`,status:'AVAILABLE',price:10000000,type:'2BHK',floor:{floorNumber:i}}));else if(url.endsWith('/hotspots'))data=[{id:'qa-info',name:'QA room',type:'info',posX:0,posY:8.05,posZ:-2,contentJson:{title:'Fixture room',description:'Read-only QA fixture'}}];else if(url.endsWith('/tours'))data=[{id:'qa-tour',name:'QA route',routeJson:[{name:'Room',posX:0,posY:8.05,posZ:1,targetX:0,targetY:8.05,targetZ:-3,dwellSeconds:30}]}];}r.fulfill({json:data});});
try{
apiMode='legacy-inventory';await page.goto(`${process.env.BASE_URL||'http://localhost:3000'}/explorer?legacy=1`,{waitUntil:'domcontentloaded'});await page.waitForTimeout(4000);await page.getByRole('button',{name:/GO INSIDE FLAT TOUR/}).click();await page.waitForTimeout(2000);await page.getByTitle('Top-down 2D floor plan blueprint',{exact:true}).click();await page.waitForTimeout(1000);await page.screenshot({path:'evidence/3d/inventory-fixture.png',fullPage:true});details.push({name:'inventory-visual-fixture',snapshot:await page.evaluate(()=>Array.from(document.querySelectorAll('*')).find(e=>e.getViewerSnapshot)?.getViewerSnapshot())});
}finally{fs.writeFileSync('evidence/3d/inventory-visual.json',JSON.stringify({results,errors,details},null,2));await browser.close();}if(results.some(r=>r.result==='FAIL')||errors.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
