const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),THREE=require('three');

const evidenceDir=process.env.EVIDENCE_DIR||'evidence/3d';fs.mkdirSync(evidenceDir,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11']});const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(20000);const results=[],errors=[],details=[];page.on('pageerror',e=>errors.push(e.message));
const test=async(name,fn)=>{try{await fn();results.push({name,result:'PASS'});}catch(e){results.push({name,result:'FAIL',reason:String(e)});}console.log(results.at(-1));};
const snapshot=()=>page.locator('[data-testid=property-canvas]').evaluate(e=>e.getViewerSnapshot());
const ready=()=>page.waitForFunction(()=>!!document.querySelector('[data-testid=property-canvas]')?.getViewerSnapshot?.().state.manifest);
let apiMode='empty';await page.route(/(?:localhost:3001|localhost:3195|trycloudflare\.com)\//,r=>{const url=r.request().url();let data=[];if(apiMode==='embed'&&url.includes('/sdk/embeds/resolve'))data={tenantId:'offline',floorPlans:[],data:[{model:{id:'bsi-duplex-v1',projectId:'offline-project',name:'Duplex Apartment',modelUrl:'/models/duplex/duplex.glb',manifestUrl:'/models/duplex/manifest.json',modelType:'exterior'},hotspots:[],tours:[]}]};if(apiMode==='legacy'){if(url.includes('theme-by-slug'))data={id:'offline',name:'Aether'};else if(url.endsWith('/digital-twin/models'))data=[{id:'exterior',projectId:'offline',name:'Exterior',modelType:'exterior',modelUrl:''},{id:'interior',projectId:'offline',name:'Interior',modelType:'interior',modelUrl:''}];else if(url.endsWith('/hotspots'))data=[{id:'qa-info',name:'QA room',type:'info',posX:0,posY:8.05,posZ:-2,contentJson:{title:'Fixture room',description:'Read-only QA fixture'}}];else if(url.endsWith('/tours'))data=[{id:'qa-tour',name:'QA route',routeJson:[{name:'Room',posX:0,posY:8.05,posZ:1,targetX:0,targetY:8.05,targetZ:-3,dwellSeconds:30}]}];}r.fulfill({json:data});});
try{
apiMode='legacy';await page.goto(`${process.env.BASE_URL||'http://localhost:3000'}/explorer?legacy=1`,{waitUntil:'domcontentloaded'});const legacySnap=()=>page.evaluate(()=>Array.from(document.querySelectorAll('*')).find(e=>e.getViewerSnapshot)?.getViewerSnapshot());await page.waitForFunction(()=>Array.from(document.querySelectorAll('*')).some(e=>e.getViewerSnapshot&&e.getViewerSnapshot().cachedGroups));
await page.waitForFunction(()=>Array.from(document.querySelectorAll('*')).some(e=>e.getViewerSnapshot&&e.getViewerSnapshot().tourCount===1),undefined,{timeout:60000});
await page.waitForTimeout(1000);
await test('Legacy floors preserve renderer and cached building',async()=>{const before=await legacySnap();for(const floor of ['02','01','02']){await page.getByRole('button',{name:new RegExp('Level '+floor)}).click();await page.waitForTimeout(250);const after=await legacySnap();assert.equal(after.stats.rendererId,before.stats.rendererId);assert.equal(after.rootId,before.rootId,JSON.stringify({before,after}));}details.push({name:'legacy-building',snapshot:await legacySnap()});});
await page.getByRole('button',{name:/GO INSIDE FLAT TOUR/}).click();await page.waitForTimeout(1600);
await test('Legacy dollhouse and floorplan preserve renderer and escape eye-height clamp',async()=>{const before=await legacySnap();await page.getByTitle('3D Dollhouse cutaway view from above',{exact:true}).click();await page.waitForTimeout(1600);let s=await legacySnap();assert.equal(s.submode,'dollhouse');assert.equal(s.stats.rendererId,before.stats.rendererId);assert(s.camera[1]>before.camera[1]+1);await page.getByTitle('Top-down 2D floor plan blueprint',{exact:true}).click();await page.waitForTimeout(1600);s=await legacySnap();assert.equal(s.submode,'floorplan');assert.equal(s.stats.rendererId,before.stats.rendererId);assert(s.camera[1]>before.camera[1]+1);await page.getByTitle('Explore inside at eye level',{exact:true}).click();await page.waitForTimeout(1600);assert.equal((await legacySnap()).submode,'inside');details.push({name:'legacy-walkthrough',snapshot:await legacySnap()});});
await test('Legacy hotspot fixture is mounted',async()=>assert.equal(await page.locator('#hotspot-overlay-qa-info').count(),1));
await test('Legacy guided tour changes camera and can pause',async()=>{const before=await legacySnap();await page.getByTitle('Play Tour',{exact:true}).click();await page.waitForTimeout(500);const playing=await legacySnap();assert(playing.tourPlaying,JSON.stringify(playing));assert.notDeepEqual(playing.camera,before.camera);await page.getByTitle('Pause Tour',{exact:true}).click();assert(await page.getByTitle('Play Tour',{exact:true}).isVisible());});
await test('Procedural door click animates its actual hinge',async()=>{
 let s=await legacySnap(),opened=null;const rect=await page.locator('canvas[data-renderer-id]').boundingBox();
 for(let view=0;view<8&&!opened;view++){
 s=await legacySnap();
 const candidates=s.doors.map(d=>{const point=new THREE.Vector3().fromArray(d.position).applyMatrix4(new THREE.Matrix4().fromArray(s.viewMatrix)).applyMatrix4(new THREE.Matrix4().fromArray(s.projection));return{door:d,point};}).filter(c=>Math.abs(c.point.x)<.9&&Math.abs(c.point.y)<.8&&c.point.z<1);
 for(const c of candidates){for(const dx of [12,-12,25,-25,40,-40]){const x=rect.x+(c.point.x+1)*rect.width/2+dx,y=rect.y+(1-c.point.y)*rect.height/2;
 if(!await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.tagName==='CANVAS',{x,y}))continue;
 await page.mouse.click(x,y);await page.waitForTimeout(150);const after=await legacySnap();opened=after.doors.find(d=>d.open&&!s.doors.find(old=>old.name===d.name)?.open);if(opened)break;}if(opened)break;}
 if(!opened){await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.4);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.75,rect.y+rect.height*.4,{steps:6});await page.mouse.up();await page.waitForTimeout(350);}
 }
 assert(opened,'No visible door opened from the tested camera');await page.waitForTimeout(1100);const after=(await legacySnap()).doors.find(d=>d.name===opened.name);assert(Math.abs(after.rotation-s.doors.find(d=>d.name===opened.name).rotation)>.5);details.push({name:'animated-door',door:after});
});
await page.screenshot({path:`${evidenceDir}/legacy-regression.png`,fullPage:true});
}finally{fs.writeFileSync(`${evidenceDir}/legacy-tests.json`,JSON.stringify({results,errors,details},null,2));await browser.close();}if(results.some(r=>r.result==='FAIL')||errors.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
